### ISSUE TITLE
Checklist about Butterfly releases

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-butterfly#36]
@dev4unet @hippo-an (cc. @MZC-CSC @innodreamer)

안녕하세요.

📅 Butterfly 0.2.x 릴리스 일정이 ~11/25(월)로 예정되어 있습니다. 

서브시스템들의 현재 릴리스 버전들을 바탕으로 Butterfly 릴리스를 진행해 주시면 될 것 같습니다.

서브시스템 간에 통합 및 테스트를 진행하시면서 기능 상 이슈가 있으실 경우 해당 서브시스템 메인테이너께 전달해 주시기 바랍니다. (사전에 협조 요청드린 상태)

(Mayfly를 통해 Cloud-Migrator platform 전체를 구동 후) Portal에서 전반적으로 테스트해 볼 계획을 가지고 있습니다. 서브시스템들의 기능이 잘 동작하는지 살펴보기 위해서 블랙박스 테스트를 수행하는 정도로 봐주시면 될 것 같습니다. 

🙋 릴리스 추진과 관련하여 이슈가 있으시면 댓글로 남겨주시기 바랍니다.

☑️ 아래 사항들에 대해 추진을 부탁드리며, 완료된 항목들은 Checked 처리하여 주십시오.
* [x] Butterfly 개발 및 테스트
* [] Butterfly 관련 서브시스템과 통합 테스트 ([Sequence Diagram](https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md) 참고 및 개선)
* [x] Butterfly 실행 지원
* [x] Butterfly 문서화
* [x] Butterfly 릴리스
각 항목별 자세한 사항은 아래 링크의 "저장소별 추진사항"을 참고하시면 될 것 같습니다.
Ref: https://github.com/cloud-barista/cloud-migrator/issues/11

(참고)
이번 Cloud-Migrator v0.3.0 통합 및 릴리스는 두 가지 측면에서 진행됩니다.

* 컴퓨팅 인프라 마이그레이션: Cloud-Migration portal에서 3종 클라우드로, 3종 자원에 대해 마이그레이션을 수행할 수 있어야 함
* SW 마이그레이션: 기능 개발, 테스트 및 통합 추진 (portal 통합 대상 X)

**Comment by yunkon-kim** [comment]
파악된 서브시스템들의 버전을 공유 드립니다. 참고 바랍니다.
* https://github.com/cloud-barista/cloud-migrator/issues/11#issuecomment-2489974389

**Comment by MZC-CSC** [comment]
@yunkon-kim 
다음 사항에 대한 추진 완료
- 콘솔 개발 및 화면 테스트
- CM-Butterfly 실행 및 실행을 위한 문서 현행화
- v0.2.2 릴리즈
- 콘솔 관점에서 필요한 서브 시스템 호출 테스트

다만 시나리오 시퀀스 다이어그램에대한 내용 검토가 마무리 되지 않아 일단 해당 내용은 unchecked 상태 유지합니다.
콘솔 코드 작업 마무리로 인해 확인 이어서 진행하도록 하겠습니다.

**Comment by yunkon-kim** [comment]
@MZC-CSC 네, 검토해보시고 수정할 부분이 있으면 편하게 공유해 주시기 바랍니다 :-)

그리고 릴리스 일정을 적절히 조정해서 공유드리겠습니다.

**Comment by yunkon-kim** [comment]
Resolved
